### ISSUE TITLE
[idea] Docker release

### ISSUE THREAD

**Issue by gigaion** [aegir-assembly/omni-clip#10]
A docker release of this open source project would be amazing and help with fast and flexible deployment of this project.

**Comment by gigaion** [comment]
Example docker configurations:


```
# Use Node.js LTS version as the base image
FROM node:lts

# Set the working directory inside the container
WORKDIR /app

# Set SHELL environment variable
ENV SHELL=/bin/bash

# Install git and SSH client
RUN apt-get update && apt-get install -y git

# Clone the repository
RUN git clone https://github.com/aegir-assembly/omni-clip.git .

# Install project dependencies
RUN npm install

# Build the project
RUN npm run build

# Expose the port app runs on
EXPOSE 8080

# Command to run the application
CMD ["npm", "start"]
```

```
version: '3'
services:
  omni-clip:
    build: .
    ports:
      - "3005:8080"
    environment:
      NODE_ENV: production
```
